version: '2.3'
services:
  tensorflow-gpu-1-14-deeplab:
    stdin_open: true
    tty: true
    command: /bin/bash
    build: .
    container_name: tensorflow-gpu-1-14-deeplab
    volumes:
      - ./:/usr/src/app
      - /data:/data
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - 9999:9999
